apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../../base
  - secret.yaml

configMapGenerator:
  - name: cloudflare-switchover-config
    behavior: merge
    literals:
      - DOMAIN_RECORDS=[{"zone_id":"faec4689c05f781fb7f3c78ee7210b95","record_name":"tardigram.com","fallback_type":"A","fallback_content":"151.115.80.213","health_check_string":"Tardigram"},{"zone_id":"d389c9eb9447d54287732dae99c19df2","record_name":"elpapeo.com","fallback_type":"A","fallback_content":"151.115.80.213","health_check_string":"ElPapeo"}]

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: imagepullsecrets-patch.yaml
    target:
      kind: Deployment
      name: cloudflare-switchover

images:
  - name: ghcr.io/nicolastobias/cloudflare-switchover
    newTag: latest
