apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-switchover
  labels:
    app: cloudflare-switchover
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloudflare-switchover
  template:
    metadata:
      labels:
        app: cloudflare-switchover
    spec:
      containers:
        - name: cloudflare-switchover
          image: ghcr.io/nicolastobias/cloudflare-switchover:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: cloudflare-switchover-config
            - secretRef:
                name: cloudflare-switchover-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: Always
